#!/bin/sh -eu
# SPDX-FileCopyrightText: (C) 2025 Rivos Inc.
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
# SPDX-License-Identifier: Apache-2.0

NODE_VERSION='latest'

if [ -z "${VIRTUAL_ENV-}" ]; then
  echo "Only run ${0} in a python virtual environment" >&2
  exit 2
elif [ -z "${1-}" ]; then
  echo "Usage: ${0} cmd [params ...]" >&2
  exit 2
fi

hash npx 2>/dev/null || nodeenv -q -p --node="${NODE_VERSION}"

exec npx -y -s "${@}"
